export enum SumsubCreateApplicantDocTypes {
  IDENTITY = 'IDENTITY',
  IDENTITY2 = 'IDENTITY2',
  SELFIE = 'SELFIE',
  PROOF_OF_RESIDENCE = 'PROOF_OF_RESIDENCE',
  PROOF_OF_PAYMENT = 'PROOF_OF_PAYMENT',
}