export enum CounterpartyTransactionsStatuses {
  KYC_AWAITING = 'KYC_AWAITING',
  KYC_PENDING = 'KYC_PENDING',
  PAYMENT_AWAITING = 'PAYMENT_AWAITING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}