export const Countries = [
  { value: 'af', iso: 'AFG', label: 'Afghanistan' },
  { value: 'ax', iso: 'ALA', label: 'Aland Islands' },
  { value: 'al', iso: 'ALB', label: 'Albania' },
  { value: 'dz', iso: 'DZA', label: 'Algeria' },
  { value: 'as', iso: 'ASM', label: 'American Samoa' },
  { value: 'ad', iso: 'AND', label: 'Andorra' },
  { value: 'ao', iso: 'AGO', label: 'Angola' },
  { value: 'ai', iso: 'AIA', label: 'Anguilla' },
  { value: 'ag', iso: 'ATG', label: 'Antigua' },
  { value: 'ar', iso: 'ARG', label: 'Argentina' },
  { value: 'am', iso: 'ARM', label: 'Armenia' },
  { value: 'aw', iso: 'ABW', label: 'Aruba' },
  { value: 'au', iso: 'AUS', label: 'Australia' },
  { value: 'at', iso: 'AUT', label: 'Austria' },
  { value: 'az', iso: 'AZE', label: 'Azerbaijan' },
  { value: 'bs', iso: 'BHS', label: 'Bahamas' },
  { value: 'bh', iso: 'BHR', label: 'Bahrain' },
  { value: 'bd', iso: 'BGD', label: 'Bangladesh' },
  { value: 'bb', iso: 'BRB', label: 'Barbados' },
  { value: 'by', iso: 'BLR', label: 'Belarus' },
  { value: 'be', iso: 'BEL', label: 'Belgium' },
  { value: 'bz', iso: 'BLZ', label: 'Belize' },
  { value: 'bj', iso: 'BEN', label: 'Benin' },
  { value: 'bm', iso: 'BMU', label: 'Bermuda' },
  { value: 'bt', iso: 'BTN', label: 'Bhutan' },
  { value: 'bo', iso: 'BOL', label: 'Bolivia' },
  { value: 'ba', iso: 'BIH', label: 'Bosnia' },
  { value: 'bw', iso: 'BWA', label: 'Botswana' },
  { value: 'bv', iso: 'BVT', label: 'Bouvet Island' },
  { value: 'br', iso: 'BRA', label: 'Brazil' },
  { value: 'vg', iso: 'VGB', label: 'British Virgin Islands' },
  { value: 'bn', iso: 'BRN', label: 'Brunei' },
  { value: 'bg', iso: 'BGR', label: 'Bulgaria' },
  { value: 'bf', iso: 'BFA', label: 'Burkina Faso' },
  { value: 'bi', iso: 'BDI', label: 'Burundi' },
  { value: 'tc', iso: 'TCA', label: 'Caicos Islands' },
  { value: 'kh', iso: 'KHM', label: 'Cambodia' },
  { value: 'cm', iso: 'CMR', label: 'Cameroon' },
  { value: 'ca', iso: 'CAN', label: 'Canada' },
  { value: 'cv', iso: 'CPV', label: 'Cape Verde' },
  { value: 'ky', iso: 'CYM', label: 'Cayman Islands' },
  { value: 'cf', iso: 'CAF', label: 'Central African Republic' },
  { value: 'td', iso: 'TCD', label: 'Chad' },
  { value: 'cl', iso: 'CHL', label: 'Chile' },
  { value: 'cn', iso: 'CHN', label: 'China' },
  { value: 'cx', iso: 'CXR', label: 'Christmas Island' },
  { value: 'cc', iso: 'CCK', label: 'Cocos Islands' },
  { value: 'co', iso: 'COL', label: 'Colombia' },
  { value: 'km', iso: 'COM', label: 'Comoros' },
  { value: 'cg', iso: 'COD', label: 'Congo Brazzaville' },
  { value: 'cd', iso: 'COG', label: 'Congo' },
  { value: 'ck', iso: 'COK', label: 'Cook Islands' },
  { value: 'cr', iso: 'CRI', label: 'Costa Rica' },
  { value: 'ci', iso: 'CIV', label: 'Cote Divoire' },
  { value: 'hr', iso: 'HRV', label: 'Croatia' },
  { value: 'cu', iso: 'CUB', label: 'Cuba' },
  { value: 'cy', iso: 'CYP', label: 'Cyprus' },
  { value: 'cz', iso: 'CZE', label: 'Czech Republic' },
  { value: 'dk', iso: 'DNK', label: 'Denmark' },
  { value: 'dj', iso: 'DJI', label: 'Djibouti' },
  { value: 'dm', iso: 'DMA', label: 'Dominica' },
  { value: 'do', iso: 'DOM', label: 'Dominican Republic' },
  { value: 'ec', iso: 'ECU', label: 'Ecuador' },
  { value: 'eg', iso: 'EGY', label: 'Egypt' },
  { value: 'sv', iso: 'SLV', label: 'El Salvador' },
  { value: 'gb', iso: 'GBR', label: 'England' },
  { value: 'gq', iso: 'GNQ', label: 'Equatorial Guinea' },
  { value: 'er', iso: 'ERI', label: 'Eritrea' },
  { value: 'ee', iso: 'EST', label: 'Estonia' },
  { value: 'et', iso: 'ETH', label: 'Ethiopia' },
  { value: 'eu', iso: 'EU', label: 'European Union' },
  { value: 'fk', iso: 'FLK', label: 'Falkland Islands' },
  { value: 'fo', iso: 'FRO', label: 'Faroe Islands' },
  { value: 'fj', iso: 'FJI', label: 'Fiji' },
  { value: 'fi', iso: 'FIN', label: 'Finland' },
  { value: 'fr', iso: 'FRA', label: 'France' },
  { value: 'gf', iso: 'GUF', label: 'French Guiana' },
  { value: 'pf', iso: 'PYF', label: 'French Polynesia' },
  { value: 'tf', iso: 'FR', label: 'French Territories' },
  { value: 'ga', iso: 'GAB', label: 'Gabon' },
  { value: 'gm', iso: 'GMB', label: 'Gambia' },
  { value: 'ge', iso: 'GEO', label: 'Georgia' },
  { value: 'de', iso: 'DEU', label: 'Germany' },
  { value: 'gh', iso: 'GHA', label: 'Ghana' },
  { value: 'gi', iso: 'GIB', label: 'Gibraltar' },
  { value: 'gr', iso: 'GRC', label: 'Greece' },
  { value: 'gl', iso: 'GRL', label: 'Greenland' },
  { value: 'gd', iso: 'GRD', label: 'Grenada' },
  { value: 'gp', iso: 'GLP', label: 'Guadeloupe' },
  { value: 'gu', iso: 'GUM', label: 'Guam' },
  { value: 'gt', iso: 'GTM', label: 'Guatemala' },
  { value: 'gw', iso: 'GNB', label: 'Guinea-Bissau' },
  { value: 'gn', iso: 'GIN', label: 'Guinea' },
  { value: 'gy', iso: 'GUY', label: 'Guyana' },
  { value: 'ht', iso: 'HTI', label: 'Haiti' },
  { value: 'hm', iso: 'HMD', label: 'Heard Island' },
  { value: 'hn', iso: 'HND', label: 'Honduras' },
  { value: 'hk', iso: 'HKG', label: 'Hong Kong' },
  { value: 'hu', iso: 'HUN', label: 'Hungary' },
  { value: 'is', iso: 'ISL', label: 'Iceland' },
  { value: 'in', iso: 'IND', label: 'India' },
  { value: 'io', iso: 'IOT', label: 'Indian Ocean Territory' },
  { value: 'id', iso: 'IDN', label: 'Indonesia' },
  { value: 'ir', iso: 'IRN', label: 'Iran' },
  { value: 'iq', iso: 'IRQ', label: 'Iraq' },
  { value: 'ie', iso: 'IRL', label: 'Ireland' },
  { value: 'il', iso: 'ISR', label: 'Israel' },
  { value: 'it', iso: 'ITA', label: 'Italy' },
  { value: 'jm', iso: 'JAM', label: 'Jamaica' },
  { value: 'jp', iso: 'JPN', label: 'Japan' },
  { value: 'jo', iso: 'JOR', label: 'Jordan' },
  { value: 'kz', iso: 'KAZ', label: 'Kazakhstan' },
  { value: 'ke', iso: 'KEN', label: 'Kenya' },
  { value: 'ki', iso: 'KIR', label: 'Kiribati' },
  { value: 'kw', iso: 'KWT', label: 'Kuwait' },
  { value: 'kg', iso: 'KGZ', label: 'Kyrgyzstan' },
  { value: 'la', iso: 'LAO', label: 'Laos' },
  { value: 'lv', iso: 'LVA', label: 'Latvia' },
  { value: 'lb', iso: 'LBN', label: 'Lebanon' },
  { value: 'ls', iso: 'LSO', label: 'Lesotho' },
  { value: 'lr', iso: 'LBR', label: 'Liberia' },
  { value: 'ly', iso: 'LBY', label: 'Libya' },
  { value: 'li', iso: 'LIE', label: 'Liechtenstein' },
  { value: 'lt', iso: 'LTU', label: 'Lithuania' },
  { value: 'lu', iso: 'LUX', label: 'Luxembourg' },
  { value: 'mo', iso: 'MAC', label: 'Macau' },
  { value: 'mk', iso: 'MKD', label: 'Macedonia' },
  { value: 'mg', iso: 'MDG', label: 'Madagascar' },
  { value: 'mw', iso: 'MWI', label: 'Malawi' },
  { value: 'my', iso: 'MYS', label: 'Malaysia' },
  { value: 'mv', iso: 'MDV', label: 'Maldives' },
  { value: 'ml', iso: 'MLI', label: 'Mali' },
  { value: 'mt', iso: 'MLT', label: 'Malta' },
  { value: 'mh', iso: 'MHL', label: 'Marshall Islands' },
  { value: 'mq', iso: 'MTQ', label: 'Martinique' },
  { value: 'mr', iso: 'MRT', label: 'Mauritania' },
  { value: 'mu', iso: 'MUS', label: 'Mauritius' },
  { value: 'yt', iso: 'MYT', label: 'Mayotte' },
  { value: 'mx', iso: 'MEX', label: 'Mexico' },
  { value: 'fm', iso: 'FSM', label: 'Micronesia' },
  { value: 'md', iso: 'MDA', label: 'Moldova' },
  { value: 'mc', iso: 'MCO', label: 'Monaco' },
  { value: 'mn', iso: 'MNG', label: 'Mongolia' },
  { value: 'me', iso: 'MNE', label: 'Montenegro' },
  { value: 'ms', iso: 'MSR', label: 'Montserrat' },
  { value: 'ma', iso: 'MAR', label: 'Morocco' },
  { value: 'mz', iso: 'MOZ', label: 'Mozambique' },
  { value: 'na', iso: 'NAM', label: 'Namibia' },
  { value: 'nr', iso: 'NRU', label: 'Nauru' },
  { value: 'np', iso: 'NPL', label: 'Nepal' },
  { value: 'an', iso: 'ANT', label: 'Netherlands Antilles' },
  { value: 'nl', iso: 'NLD', label: 'Netherlands' },
  { value: 'nc', iso: 'NCL', label: 'New Caledonia' },
  { value: 'pg', iso: 'PNG', label: 'New Guinea' },
  { value: 'nz', iso: 'NZL', label: 'New Zealand' },
  { value: 'ni', iso: 'NIC', label: 'Nicaragua' },
  { value: 'ne', iso: 'NER', label: 'Niger' },
  { value: 'ng', iso: 'NGA', label: 'Nigeria' },
  { value: 'nu', iso: 'NIU', label: 'Niue' },
  { value: 'nf', iso: 'NFK', label: 'Norfolk Island' },
  { value: 'kp', iso: 'PRK', label: 'North Korea' },
  { value: 'mp', iso: 'MNP', label: 'Northern Mariana Islands' },
  { value: 'no', iso: 'NOR', label: 'Norway' },
  { value: 'om', iso: 'OMN', label: 'Oman' },
  { value: 'pk', iso: 'PAK', label: 'Pakistan' },
  { value: 'pw', iso: 'PLW', label: 'Palau' },
  { value: 'ps', iso: 'PSE', label: 'Palestine' },
  { value: 'pa', iso: 'PAN', label: 'Panama' },
  { value: 'py', iso: 'PRY', label: 'Paraguay' },
  { value: 'pe', iso: 'PER', label: 'Peru' },
  { value: 'ph', iso: 'PHL', label: 'Philippines' },
  { value: 'pn', iso: 'PCN', label: 'Pitcairn Islands' },
  { value: 'pl', iso: 'POL', label: 'Poland' },
  { value: 'pt', iso: 'PRT', label: 'Portugal' },
  { value: 'pr', iso: 'PRI', label: 'Puerto Rico' },
  { value: 'qa', iso: 'QAT', label: 'Qatar' },
  { value: 're', iso: 'REU', label: 'Reunion' },
  { value: 'ro', iso: 'ROU', label: 'Romania' },
  { value: 'ru', iso: 'RUS', label: 'Russia' },
  { value: 'rw', iso: 'RWA', label: 'Rwanda' },
  { value: 'sh', iso: 'SHN', label: 'Saint Helena' },
  { value: 'kn', iso: 'KNA', label: 'Saint Kitts and Nevis' },
  { value: 'lc', iso: 'LCA', label: 'Saint Lucia' },
  { value: 'pm', iso: 'SPM', label: 'Saint Pierre' },
  { value: 'vc', iso: 'VCT', label: 'Saint Vincent' },
  { value: 'ws', iso: 'WSM', label: 'Samoa' },
  { value: 'sm', iso: 'SMR', label: 'San Marino' },
  { value: 'gs', iso: 'SGS', label: 'Sandwich Islands' },
  { value: 'st', iso: 'STP', label: 'Sao Tome' },
  { value: 'sa', iso: 'SAU', label: 'Saudi Arabia' },
  { value: 'sn', iso: 'SEN', label: 'Senegal' },
  { value: 'cs', iso: 'SRB', label: 'Serbia' },
  { value: 'rs', iso: 'SRB', label: 'Serbia' },
  { value: 'sc', iso: 'SYC', label: 'Seychelles' },
  { value: 'sl', iso: 'SLE', label: 'Sierra Leone' },
  { value: 'sg', iso: 'SGP', label: 'Singapore' },
  { value: 'sk', iso: 'SVK', label: 'Slovakia' },
  { value: 'si', iso: 'SVN', label: 'Slovenia' },
  { value: 'sb', iso: 'SLB', label: 'Solomon Islands' },
  { value: 'so', iso: 'SOM', label: 'Somalia' },
  { value: 'za', iso: 'ZAF', label: 'South Africa' },
  { value: 'kr', iso: 'KOR', label: 'South Korea' },
  { value: 'es', iso: 'ESP', label: 'Spain' },
  { value: 'lk', iso: 'LKA', label: 'Sri Lanka' },
  { value: 'sd', iso: 'SDN', label: 'Sudan' },
  { value: 'sr', iso: 'SUR', label: 'Suriname' },
  { value: 'sj', iso: 'SJM', label: 'Svalbard' },
  { value: 'sz', iso: 'SWZ', label: 'Swaziland' },
  { value: 'se', iso: 'SWE', label: 'Sweden' },
  { value: 'ch', iso: 'CHE', label: 'Switzerland' },
  { value: 'sy', iso: 'SYR', label: 'Syria' },
  { value: 'tw', iso: 'TWN', label: 'Taiwan' },
  { value: 'tj', iso: 'TJK', label: 'Tajikistan' },
  { value: 'tz', iso: 'TZA', label: 'Tanzania' },
  { value: 'th', iso: 'THA', label: 'Thailand' },
  { value: 'tl', iso: 'TLS', label: 'Timorleste' },
  { value: 'tg', iso: 'TGO', label: 'Togo' },
  { value: 'tk', iso: 'TKL', label: 'Tokelau' },
  { value: 'to', iso: 'TON', label: 'Tonga' },
  { value: 'tt', iso: 'TTO', label: 'Trinidad' },
  { value: 'tn', iso: 'TUN', label: 'Tunisia' },
  { value: 'tr', iso: 'TUR', label: 'Turkey' },
  { value: 'tm', iso: 'TKM', label: 'Turkmenistan' },
  { value: 'tv', iso: 'TUV', label: 'Tuvalu' },
  { value: 'ug', iso: 'UGA', label: 'Uganda' },
  { value: 'ua', iso: 'UKR', label: 'Ukraine' },
  { value: 'ae', iso: 'ARE', label: 'United Arab Emirates' },
  { value: 'us', iso: 'USA', label: 'United States' },
  { value: 'uy', iso: 'URY', label: 'Uruguay' },
  { value: 'um', iso: 'UMI', label: 'Us Minor Islands' },
  { value: 'vi', iso: 'VIR', label: 'Us Virgin Islands' },
  { value: 'uz', iso: 'UZB', label: 'Uzbekistan' },
  { value: 'vu', iso: 'VUT', label: 'Vanuatu' },
  { value: 'va', iso: 'VA', label: 'Vatican City' },
  { value: 've', iso: 'VEN', label: 'Venezuela' },
  { value: 'vn', iso: 'VNM', label: 'Vietnam' },
  { value: 'wf', iso: 'WLF', label: 'Wallis and Futuna' },
  { value: 'eh', iso: 'ESH', label: 'Western Sahara' },
  { value: 'ye', iso: 'YEM', label: 'Yemen' },
  { value: 'zm', iso: 'ZMB', label: 'Zambia' },
  { value: 'zw', iso: 'ZWE', label: 'Zimbabwe' },
];